apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zicops-course-creator
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /cc/?(.*)
            pathType: Prefix  
            backend:
              service:
                name: zicops-course-creator
                port:
                  number: 80