input QuestionBankInput {
    id: ID
    name: String
    category: String
    sub_category: String
    created_at: String
    updated_at: String
    created_by: String
    updated_by: String
    is_active: Boolean
    is_default: Boolean
    owner: String
}

type QuestionBank {
    id: ID
    name: String
    category: String
    sub_category: String
    created_at: String
    updated_at: String
    created_by: String
    updated_by: String
    is_active: Boolean
    is_default: Boolean
    owner: String
}

type QuestionBankQuestion {
    id: ID
    Description: String
    Type: String
    Difficulty: Int
    Attachment: String
    AttachmentType: String
    Hint : String
    QbmId: String
    Status: String
    CreatedAt: String
    UpdatedAt: String
    CreatedBy: String
    UpdatedBy: String
}

input QuestionBankQuestionInput {
    id: ID
    Description: String
    Type: String
    Difficulty: Int
    File: Upload
    AttachmentType: String
    Hint : String
    QbmId: String
    Status: String
    CreatedAt: String
    UpdatedAt: String
    CreatedBy: String
    UpdatedBy: String
}

type QuestionOption {
    id: ID
    QmId: String
    Description: String
    IsCorrect: Boolean
    CreatedAt: String
    UpdatedAt: String
    CreatedBy: String
    UpdatedBy: String
    AttachmentType: String
    Attachment: String
    IsActive : Boolean
}

input QuestionOptionInput {
    id: ID
    QmId: String
    Description: String
    IsCorrect: Boolean
    CreatedAt: String
    UpdatedAt: String
    CreatedBy: String
    UpdatedBy: String
    AttachmentType: String
    File: Upload
    IsActive : Boolean
}

type Mutation{
    createQuestionBank(input: QuestionBankInput): QuestionBank
    updateQuestionBank(input: QuestionBankInput): QuestionBank
    addQuestionBankQuestion(input: QuestionBankQuestionInput): QuestionBankQuestion
    updateQuestionBankQuestion(input: QuestionBankQuestionInput): QuestionBankQuestion
    addQuestionOptions(input: QuestionOptionInput): QuestionOption
    updateQuestionOptions(input: QuestionOptionInput): QuestionOption
}
