name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: zicops-one    # TODO: update to cluster name
  GKE_ZONE: asia-southeast1-a   # TODO: update to cluster zone
  SERVICE_NAME: zicops-course-creator
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
 # Build docker image
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Build the Docker image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA --build-arg GO_MODULES_TOKEN=${secrets.GO_MODULES_TOKEN} .
    - run: |
        gcloud auth configure-docker -q
    - name: Push image to GCP
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Deploy to zicops-one
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade zicops-course-creator k8s/zicops-course-creator --install --wait --atomic